# Generated by Django 5.1 on 2024-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='weather',
            field=models.IntegerField(max_length=2),
        ),
    ]
