# Generated by Django 5.1 on 2024-08-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='weather',
        ),
    ]
