# Generated by Django 5.1 on 2024-08-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destination_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='weather',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
